language: node_js
node_js: 
	- node
 	- iojs
	
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
 
before_install:
 	- sudo apt-get update -qq
 	- sudo apt-get install -qq [packages list]
install:
  - npm install
  - npm run install-all

services:
	- mongodb

script: bundle exec thor build

deploy:
  skip_cleanup: true
 